/*!CK:1653309043!*//*1408333604,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["jlcAE"]); }

__d("ActivityLogSearch",["Event","CSS","DOM","Input","Run"],function(a,b,c,d,e,f,g,h,i,j,k){function l(m,n,o){var p=i.find(o,'.inputtext'),q=g.listen(n,'click',function(){h.hide(m);h.show(o);p.focus();});k.onLeave(q.remove.bind(q));var r=g.listen(p,'blur',function(){if(!j.getValue(p)){h.hide(o);h.show(m);}});k.onLeave(r.remove.bind(r));}e.exports=l;},null);
__d("ScrollHighlight",["DOMScroll","highlight"],function(a,b,c,d,e,f,g,h){var i={actOn:function(j,k,l){g.scrollTo(j,true,false,false,l);h(j,null,k);}};e.exports=i;},null);
__d("ProfileApprovalController",["AsyncRequest","DOM","Event","HTML","$","copyProperties","ge"],function(a,b,c,d,e,f,g,h,i,j,k,l,m){function n(o){"use strict";this.queueType=o;var p=m('profileApprovalSeeMoreLink');if(p)i.listen(p,'click',this.clickedSeeMore.bind(this));}n.prototype.getNewStories=function(){"use strict";var o=this.getStoryData(),p={filter:this.FILTER_NEWER,filter_timestamp:o.newest_time,filter_fbid:o.newest_fbid};new g().setURI('/ajax/profile/approval/get_more.php').setData(p).setHandler(this.handleContent).send();};n.prototype.clickedSeeMore=function(){"use strict";var o=this.getStoryData(),p={queue_type:this.queueType,filter:this.FILTER_OLDER,filter_timestamp:o.oldest_time,filter_fbid:o.oldest_fbid};new g().setURI('/ajax/profile/approval/get_more.php').setData(p).setHandler(this.handleContent).send();};n.prototype.handleContent=function(o){"use strict";var p=o.payload;if(p.pager_error){h.replace(k('profileApprovalSeeMoreContainer'),j(p.pager_markup));return;}if(p.hide_more_pager)h.remove(k('profileApprovalSeeMoreContainer'));if(!p.items_markup)return;if(p.insert_before)h.prependContent(h.find(k('profileApprovalContentContainer'),'.profileApprovalList'),j(p.items_markup));if(p.insert_after)h.appendContent(h.find(k('profileApprovalContentContainer'),'.profileApprovalList'),j(p.items_markup));};n.prototype.getStoryData=function(){"use strict";var o=h.scry(k('profileApprovalContentContainer'),'.profileApprovalStoryContainer');if(!o)return;var p=o[0],q=o[o.length-1];return {newest_time:p.getAttribute('data-timestamp'),newest_fbid:p.getAttribute('data-fbid'),oldest_time:q.getAttribute('data-timestamp'),oldest_fbid:q.getAttribute('data-fbid')};};n.NO_MORE_CONTENT='no_more_content';l(n.prototype,{FILTER_NONE:0,FILTER_OLDER:1,FILTER_NEWER:2});e.exports=n;},null);
__d("legacy:profile-approval-controller",["ProfileApprovalController"],function(a,b,c,d){a.ProfileApprovalController=b('ProfileApprovalController');},3);
__d("ConfirmFamilyPendingPostsQueue",["Event","Button","DOM"],function(a,b,c,d,e,f,g,h,i){var j={listen:function(k){g.listen(k,'change',function(event){var l=event.target,m=!!parseInt(l.value,10),n=l.form;n.approve_button.disabled=!m;var o=i.find(n,'.submitButton');h.setEnabled(o,m);});}};e.exports=j;},null);
__d("ApprovalQueueCountUpdater",["ge","Arbiter","DOM"],function(a,b,c,d,e,f,g,h,i){var j={updateCounts:function(k,l){var m=k.friends+k.others,n=g('tag_count_friends'),o=g('tag_count_other');h.inform('NavigationMessage/navigationCount',{key:'review',count:m,hide:true});i.setContent(n,k.friends<=l?k.friends:l+"+");i.setContent(o,k.others<=l?k.others:l+"+");}};e.exports=j;},null);
__d("TimelineReviewTour",["AsyncRequest"],function(a,b,c,d,e,f,g){var h={showTour:function(i){new g().setURI('/ajax/timeline/all_activity/review/tour.php').setData({step:i}).send();}};e.exports=h;},null);