/*!CK:2443981599!*//*1408934901,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["1ncDu"]); }

__d("GroupsMemberCountUpdater",["Arbiter","DOM"],function(a,b,c,d,e,f,g,h){function i(){}i.subscribeMemberCount=function(j){g.subscribe('GroupsMemberCount/changeText',function(k,l){h.setContent(j,l);});};i.subscribeNewMemberCount=function(j){g.subscribe('GroupsMemberCount/changeNewMembersText',function(k,l){h.setContent(j,l);});};e.exports=i;},null);
__d("NotificationsSelector",["Parent","submitForm","AsyncRequest"],function(a,b,c,d,e,f,g,h,i){function j(l,m,n){m.subscribe('change',function(o,p){n.value=p.value;var q=g.byTag(l,'form');q&&h(q);});}function k(l,m,n,o){m.subscribe('change',function(p,q){new i().setURI('/ajax/groups/notifications/update.php').setData({setting:q.value,group_id:o}).setMethod('POST').send();});}e.exports.bindForm=j;e.exports.updateNotif=k;},null);
__d("GroupSearchBox",["CSS","DOM","Event","Input","Parent"],function(a,b,c,d,e,f,g,h,i,j,k){var l={init:function(m,n){var o=h.find(n,'.inputtext'),p=k.byClass(o,'searchBoxToggle');i.listen(m,'click',function(){g.show(n);o.focus();p&&g.addClass(p,'searchBoxVisible');});i.listen(o,'blur',function(){if(!j.getValue(o)){g.hide(n);p&&g.removeClass(p,'searchBoxVisible');}});}};e.exports=l;},null);
__d("GroupsAddTypeaheadView",["Arbiter","ContextualTypeaheadView"],function(a,b,c,d,e,f,g,h){for(var i in h)if(h.hasOwnProperty(i))k[i]=h[i];var j=h===null?null:h.prototype;k.prototype=Object.create(j);k.prototype.constructor=k;k.__superConstructor__=h;function k(){"use strict";if(h!==null)h.apply(this,arguments);}k.prototype.select=function(l){"use strict";var m=this.results[this.index];g.inform('GroupsMemberSuggestion/remove',m.uid);if(m.is_member){this.reset();}else j.select.call(this,l);};e.exports=k;},null);
__d("GroupsAddMemberTypeahead",["Arbiter","DOM","Typeahead","copyProperties","ge"],function(a,b,c,d,e,f,g,h,i,j,k){function l(m,n){if(m&&n)this.init(m,n);}j(l.prototype,{init:function(m,n){m.subscribe('select',function(o,p){g.inform('GroupsAddMemberTypeahead/add',{gid:n,uid:p.selected.uid,name:p.selected.text,photo:p.selected.photo});var q=m.getData().getExclusions();q.push(p.selected.uid);m.getData().setExclusions(q);});g.subscribe('GroupsAddMemberTypeahead/updateGroupToken',this.resetTypeaheadCaches.bind(this));},resetTypeaheadCaches:function(m,n){var o=h.scry(k('pagelet_group_'),'.uiTypeahead:not(.uiPlacesTypeahead)');for(var p=0;p<o.length;p++){var q=i.getInstance(o[p]);if(q){var r=q.getData();r.updateToken(n.token);q.getCore().subscribe('focus',r.bootstrap.bind(r));}}}});e.exports=l;},null);
__d("legacy:GroupsAddMemberTypeahead",["GroupsAddMemberTypeahead"],function(a,b,c,d){a.GroupsAddMemberTypeahead=b('GroupsAddMemberTypeahead');},3);
__d("LitestandRHCAds",["AdsRefreshHandler","Arbiter","DOM","Event","LitestandMessages","NavigationMessage","Run","SubscriptionsHandler","csx","ge"],function(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p){var q,r,s,t,u;function v(){r&&r.forceLoadIfEnoughTimePassed(0);}function w(){var ba=i.scry(s,"._5f85 a")[0];if(ba)q.addSubscriptions(j.listen(ba,'click',v));}function x(){var ba=p(t);if(ba&&u){ba.appendChild(u);u=null;}}function y(){if(r){r.cleanup();r=null;}if(q){q.release();q=null;}u=null;}function z(ba,ca){u=ca;v();}var aa={init:function(ba,ca,da){s=p(ba);t=ba;r=new g(s,ca,da).subscribeDefaultEventsForRefresh();q=new n();q.addSubscriptions(h.subscribe(l.NAVIGATION_BEGIN,y),h.subscribe('AdsRefreshHandler/AdsLoaded',w),h.subscribe('AdsRefreshHandler/AdsLoaded',x),h.subscribe('ProfileQuestionAnswered',z));w();m.onLeave(y);}};e.exports=aa;},null);
__d("PopoverMenuDynamicIcon",["Button","CSS","DOM","DOMQuery","copyProperties","csx"],function(a,b,c,d,e,f,g,h,i,j,k,l){function m(n){"use strict";this._popoverMenu=n;}m.prototype.enable=function(){"use strict";this._setMenuSubscription=this._popoverMenu.subscribe('setMenu',this._onSetMenu.bind(this));};m.prototype.disable=function(){"use strict";this._popoverMenu.unsubscribe(this._setMenuSubscription);this._setMenuSubscription=null;this._removeChangeSubscription();};m.prototype._onSetMenu=function(){"use strict";this._removeChangeSubscription();this._menu=this._popoverMenu.getMenu();this._changeSubscription=this._menu.subscribe('change',function(n,o){var p=o.item;if(o[0])p=o[0].item;if(!p)return;var q=p.getIcon();q=q?q.cloneNode(true):null;var r=this._popoverMenu.getTriggerElem(),s=j.scry(r,"span._55pe")[0];if(s){var t=s.firstChild;if(h.hasClass(t,'img')){i.replace(t,q);}else i.prependContent(s,q);}else g.setIcon(r,q);}.bind(this));};m.prototype._removeChangeSubscription=function(){"use strict";if(this._changeSubscription){this._menu.unsubscribe(this._changeSubscription);this._changeSubscription=null;}};k(m.prototype,{_setMenuSubscription:null,_changeSubscription:null});e.exports=m;},null);
__d("TypeaheadSubmitOnSelect",["Form","copyProperties"],function(a,b,c,d,e,f,g,h){function i(j){"use strict";this._typeahead=j;}i.prototype.enable=function(){"use strict";this._subscription=this._typeahead.subscribe('select',function(){var j=this._typeahead.getCore().getElement().form;if(j)j.getAttribute('rel')=='async'?g.bootstrap(j):j.submit();}.bind(this));};i.prototype.disable=function(){"use strict";this._typeahead.unsubscribe(this._subscription);this._subscription=null;};h(i.prototype,{_subscription:null});e.exports=i;},null);
__d("legacy:SubmitOnSelectTypeaheadBehavior",["TypeaheadSubmitOnSelect"],function(a,b,c,d,e,f,g){if(!a.TypeaheadBehaviors)a.TypeaheadBehaviors={};a.TypeaheadBehaviors.submitOnSelect=function(h){h.enableBehavior(g);};},3);